import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Index page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="font-bold text-red-500 text-3xl">Im a index page</h1>
    </>
  )
}
